config/routes.rb
Howto::Application.routes.draw do

  resources :how_tos do
    resources :steps
  end

  root 'how_tos#index'

end

app/models/how_to.rb
class HowTo < ActiveRecord::Base
  validates :title, :presence => true

  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :how_to
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/how_tos_controller.rb
class HowTosController < ApplicationController
  before_action :set_how_to, only: [:show, :edit, :update, :destroy]

  # GET /how_tos
  # GET /how_tos.json
  def index
    @how_tos = HowTo.all
  end

  # GET /how_tos/1
  # GET /how_tos/1.json
  def show
    @steps = @how_to.steps
  end

  # GET /how_tos/new
  def new
    @how_to = HowTo.new
  end

  # GET /how_tos/1/edit
  def edit
  end

  # POST /how_tos
  # POST /how_tos.json
  def create
    @how_to = HowTo.new(how_to_params)

    respond_to do |format|
      if @how_to.save
        format.html { redirect_to @how_to, notice: 'How to was successfully created.' }
        format.json { render action: 'show', status: :created, location: @how_to }
      else
        format.html { render action: 'new' }
        format.json { render json: @how_to.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /how_tos/1
  # PATCH/PUT /how_tos/1.json
  def update
    respond_to do |format|
      if @how_to.update(how_to_params)
        format.html { redirect_to @how_to, notice: 'How to was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @how_to.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /how_tos/1
  # DELETE /how_tos/1.json
  def destroy
    @how_to.destroy
    respond_to do |format|
      format.html { redirect_to how_tos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_how_to
      @how_to = HowTo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def how_to_params
      params.require(:how_to).permit(:title, :description)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_how_to
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
 def index
    @steps = @how_to.steps
  end

  # GET /steps/1
  # GET /steps/1.json
  def show

    respond_to do |format|
      format.html
      format.xml { render :xml => @step }
    end
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @how_to.steps.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to([@step.how_to, @step], notice: 'Step was successfully created.') }
        format.json { render action: 'show', status: :created, location: @step }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to how_to_step_path(@how_to,@step), notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to how_to_steps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_how_to
      @how_to = HowTo.find(params[:how_to_id])
    end

    def set_step
      @step = @how_to.steps.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:instructions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/how_tos_helper.rb
module HowTosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/how_tos/_form.html.erb
<%= form_for(@how_to) do |f| %>
  <% if @how_to.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@how_to.errors.count, "error") %> prohibited this how_to from being saved:</h2>

      <ul>
      <% @how_to.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/how_tos/edit.html.erb
<h1>Editing how_to</h1>

<%= render 'form' %>

<%= link_to 'Show', [@how_to, @step] %> |
<%= link_to 'Back', how_tos_path %>

app/views/how_tos/index.html.erb
<h1>How Tos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @how_tos.each do |how_to| %>
      <tr>
        <td><%= how_to.title %></td>
        <td><%= how_to.description %></td>
        <td><%= link_to 'Show', how_to %></td>
        <td><%= link_to 'Edit', edit_how_to_path(how_to) %></td>
        <td><%= link_to 'Destroy', how_to, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New How to', new_how_to_path %>

app/views/how_tos/new.html.erb
<h1>New how_to</h1>

<%= render 'form' %>

<%= link_to 'Back', how_tos_path %>

app/views/how_tos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @how_to.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @how_to.description %>
</p>

<table>
  <tbody>
    <% @steps.each do |step| %>
    <tr>
      <td><%= step.instructions %></td>
    </tr>
    <% end %>
</table>

<br>
<%= link_to 'Edit', edit_how_to_path(@how_to) %> |
<%= link_to 'Back', how_tos_path %> |
<%= link_to 'New Step', new_how_to_step_path(@how_to) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>How To Survive Code Fellows</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@how_to, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', how_to_step_path(@how_to, @step) %> |
<%= link_to 'Back', how_to_steps_path(@how_to) %>

app/views/steps/index.html.erb
<h1>How to Survive Code Fellows</h1>

<table>
  <thead>
    <tr>
      <th>Instructions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.instructions %></td>
        <td><%= link_to 'Show', [step.how_to, step] %></td>
        <td><%= link_to 'Edit', edit_how_to_step_path(@how_to, step) %></td>
        <td><%= link_to 'Destroy', [step.how_to, step], data: { confirm: 'Are you sure?' }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_how_to_step_path %> |
<%= link_to 'Home', how_tos_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', how_to_steps_path(@how_to) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructions:</strong>
  <%= @step.instructions %>
</p>

<%= link_to 'Edit', edit_how_to_step_path(@step.how_to, @step) %> |
<%= link_to 'Back', how_to_steps_path(@step.how_to) %>